[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:$PORT --workers 2 stockcompass.wsgi:application"
