# Generated by Django 4.2 on 2025-02-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('time_published', models.DateTimeField()),
                ('summary', models.TextField()),
                ('banner_image', models.URLField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('overall_sentiment_score', models.FloatField()),
            ],
        ),
    ]
