# Generated by Django 4.2 on 2025-02-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='banner_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='overall_sentiment_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='source',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='time_published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='title',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
