# Generated by Django 4.2 on 2025-02-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='pct_change',
            field=models.FloatField(default=0.0),
        ),
    ]
