# Generated by Django 4.2 on 2025-02-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0002_stockdata_pct_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='eps',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='free_cash_flow',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='market_cap',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='pe',
            field=models.FloatField(default=0.0),
        ),
    ]
