# Generated by Django 4.2 on 2025-02-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0003_stockdata_eps_stockdata_free_cash_flow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='eps',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='free_cash_flow',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='market_cap',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='pct_change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='pe',
            field=models.FloatField(null=True),
        ),
    ]
