# Generated by Django 4.2 on 2025-02-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0004_alter_stockdata_eps_alter_stockdata_free_cash_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='profit_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='dividends',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='free_cash_flow',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='market_cap',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='pct_change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='pe',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='stock_splits',
            field=models.FloatField(default=0),
        ),
    ]
