# Generated by Django 4.2 on 2025-02-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0005_stockdata_profit_margin_alter_stockdata_dividends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='dividends',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='stock_splits',
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='close_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='eps',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='free_cash_flow',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='market_cap',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='pct_change',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='pe',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='profit_margin',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='volume',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
